from os import strerror

try:
    fo = open()